### ISSUE TITLE
Convert vtkImageData to an itk::Image example in Python does not work

### ISSUE THREAD

**Issue by alkamid** [InsightSoftwareConsortium/ITK#1895]
### Description

Example code in https://itk.org/ITKExamples/src/Bridge/VtkGlue/ConvertvtkImageDataToAnitkImage/Documentation.html#python raises an exception.

### Steps to Reproduce

```
>pip install itk-vtkglue Pillow
>pip list
Package          Version
---------------- -----------
itk              5.1.0.post3
itk-core         5.1.0.post3
itk-filtering    5.1.0.post3
itk-io           5.1.0.post3
itk-numerics     5.1.0.post3
itk-registration 5.1.0.post3
itk-segmentation 5.1.0.post3
itk-vtkglue      0.3.0
numpy            1.19.0
Pillow           7.1.2
pip              19.2.3
setuptools       41.2.0
vtk              8.1.2

```

Run the example (modified to be self-contained rather than requiring an input image):
```python
import itk
import vtk
from PIL import Image
import numpy as np

imageFileName = "/tmp/glue_test.png"
test_image = np.zeros((10, 10, 3), dtype=np.uint8)
im = Image.fromarray(test_image)
im.save(imageFileName)

Dimension = 2
PixelType = itk.UC
ImageType = itk.Image[PixelType, Dimension]

reader = vtk.vtkPNGReader()
reader.SetFileName(imageFileName)
reader.SetDataScalarTypeToUnsignedChar()

magnitude = vtk.vtkImageMagnitude()
magnitude.SetInputConnection(reader.GetOutputPort())
magnitude.Update()

vtkToItkFilter = itk.VTKImageToImageFilter[ImageType].New()
vtkToItkFilter.SetInput(magnitude.GetOutput())

vtkToItkFilter.Update()
myitkImage = vtkToItkFilter.GetOutput()
print(myitkImage)
```

This raises an exception:
```
>python vtkexample.py
Traceback (most recent call last):
  File "vtkexample.py", line 24, in <module>
    vtkToItkFilter = itk.VTKImageToImageFilter[ImageType].New()
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itkBase.py", line 99, in LoadModule
    module = loader.load(swig_module_name)
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itkBase.py", line 220, in load
    module.__loader__.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itk/ITKVtkGluePython.py", line 130, in <module>
    from itkBoxSpatialObjectToVTKPolyDataFilterPython import *
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itk/Configuration/../itkBoxSpatialObjectToVTKPolyDataFilterPython.py", line 106, in <module>
    import ITKCommonBasePython
  File "/home/vtk_testvenv/lib/python3.7/site-packages/itk/Configuration/../ITKCommonBasePython.py", line 8, in <module>
    from . import _ITKCommonPython
ImportError: attempted relative import with no known parent package

```
### Environment

Ubuntu 18.04, Python 3.7.6.

**Comment by thewtex** [comment]
Thanks for the report. The `itk-vtkglue` is currently out of date.

Please help up test and use these functions:

https://github.com/InsightSoftwareConsortium/ITK/blob/ccf8132f1604ecf2937e92a1c3f7e3673c3137ff/Wrapping/Generators/Python/itkExtras.py#L459-L524

These will ship with `itk-5.2.0`.

**Comment by alkamid** [comment]
Thanks for that @thewtex ! My use case (`vtkPolyData` -> `vtkTransformPolyDataFilter` -> `vtkPolyDataToImageStencil` -> ITK image) works fine with the code you linked. Looking forward to v5.2.0!

**Comment by thewtex** [comment]
This is can now be installed with

```
pip install --upgrade --pre itk
```
