### ISSUE TITLE
Python Wrapping: UnaryFunctorImageFilter issue when building with RTK

### ISSUE THREAD

**Issue by MrTzschr** [InsightSoftwareConsortium/ITK#2064]
### Description

Python wrapping is not working with recent commits to ITK master as UnaryFunctorImageFilter (and maybe others) is missing(?).  I encountered this when compiling with `ITK_WRAP_PYTHON=ON` and `Module_RTK=ON` but as this is an ITK Filter I suspect that this is not an RTK dependent issue.
Maybe this is more relevant to @SimonRit and RTK?
The build itself compiles without errors but the wrapping is incomplete (see example below).

### Steps to Reproduce

Clone current master, Build Release with `ITK_WRAP_PYTHON=ON` and `Module_RTK=ON` using MSVC or ninja.
Open python shell and execute commands given below.

### Expected behavior
```
import itk
itk.Image
<itkTemplate itk::Image>

from itk import RTK as rtk
rtk.Image
<itkTemplate itk::Image>

itk.UnaryFunctorImageFilter
<itkTemplate itk::UnaryFunctorImageFilter>
```
### Actual behavior

```
import itk
itk.Image

<itkTemplate itk::Image>

from itk import RTK as rtk
rtk.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 101, in LoadModule
    LoadModule(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 101, in LoadModule
    LoadModule(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 215, in LoadModule
    init_function()
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\itkVectorRescaleIntensityImageFilterPython.py", line 791, in unary_functor_image_filter_init_docstring
    if isinstance(itk.UnaryFunctorImageFilter, itkTemplate.itkTemplate):
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 70, in LoadModule
    assert hasattr(this_module, "swig")
AssertionError

itk.UnaryFunctorImageFilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 70, in LoadModule
    assert hasattr(this_module, "swig")
AssertionError
```

### Reproducibility

100%

### Versions

ITK 5.1.1 master
but ITKConfig.cmake actually uses
```
set(ITK_VERSION_MAJOR "5")
set(ITK_VERSION_MINOR "2")
set(ITK_VERSION_PATCH "0")
```

### Environment

CMake 3.17.5
VS2019, v16.7.6 or ninja v1.10.1
Python 3.8.3 from Anaconda3 (2020.07)
Windows 10

### Additional Information

I suspect one of the recent commits to be the issue as I tried some of the older ones and saw that [at least everything works up to this commit](https://github.com/InsightSoftwareConsortium/ITK/commit/4c0982ddec474b1701d695839c78c7e888659ef4). Maybe even some of the following commits work but I didn't have time to check all of them.
As I don't know what actually went wrong I do not what I am looking for.

For the builds mentioned above I used ninja but MSVC behaves similar, just takes way longer to build everything.
I also tried to set `Module_RTK_GIT_TAG=master` as I thought RTK may be the culprit but this does not change anything.

**Comment by SimonRit** [comment]
Thanks for the report, I will have a look and let you know my findings.

**Comment by dzenanz** [comment]
PRs #2061 and #2063 might be related.

**Comment by SimonRit** [comment]
After recompiling with ITK master and RTK master (Linux, cmake 3.13, gcc 7.3.1), I have the expected behavior. Can you confirm that your RTK master included SimonRit/RTK@8ac7f0b2870ad9f6d9179c4b638bbd3b3bc1c8b5 which corrects for 4c0982ddec474b1701d695839c78c7e888659ef4? If yes, I'll try to compile on Windows...

**Comment by MrTzschr** [comment]
Hi @SimonRit and thanks for looking into it. My rtkVersion.ggo shows
`version "2.1.0, git hash 04caaaace8e2789a73af22e282a41e2141b78232"` (https://github.com/SimonRit/RTK/commit/04caaaace8e2789a73af22e282a41e2141b78232)
so it should include the corrections you mentioned.
Anything else I can try on my side?

**Comment by SimonRit** [comment]
Yes, it should include it. Can you also provide the ITK git tag? What's the value of RTK_USE_CUDA in your CMakeCache.txt file?

**Comment by MrTzschr** [comment]
ITK: abd70cea64cc8368b77cee5a33f859f7da387fda (https://github.com/InsightSoftwareConsortium/ITK/commits/abd70cea64cc8368b77cee5a33f859f7da387fda)
and `RTK_USE_CUDA:BOOL=ON`

For the sake of completness, my CMake flags using ninja were:
```
CMAKE_BUILD_TYPE=Release
BUILD_EXAMPLES=OFF
BUILD_SHARED_LIBS=OFF
BUILD_TESTING=OFF
ITK_WRAP_PYTHON=ON
Module_RTK=ON
Module_RTK_GIT_TAG=master
```

**Comment by SimonRit** [comment]
Thanks. I can now reproduce on my linux box, it was a mistake on my side. I'll git bisect to find out when the problem was introduced, it's probably one in the PRs pointed out by @dzenanz.

**Comment by SimonRit** [comment]
The problem has been introduced by 183cb1db67c5dbd30a25f279f913a4d2da5ea0b6. Maybe @hjmjohnson knows what is the issue here? I'm quite lost in this code so I don't even know if it's an RTK or ITK issue...

**Comment by MrTzschr** [comment]
Any update on this? @hjmjohnson can you comment on the changes you made that seem to break the python wrapping? I also saw @thewtex's comment at https://github.com/InsightSoftwareConsortium/ITK/commit/183cb1db67c5dbd30a25f279f913a4d2da5ea0b6#r43450044

**Comment by dzenanz** [comment]
Is this issue still present?

**Comment by MrTzschr** [comment]
@dzenanz thanks for bringing this up again. Sadly nothing changed, so yes, the issue is still present.
A (slightly) updated output looks like this as things moved from `LoadModule` to `itk_load_swig_module`:

```
>>> import itk
>>> itk.Image
<itkTemplate itk::Image>
>>> from itk import RTK as rtk
>>> rtk.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkLazy.py", line 78, in __getattribute__
    itkBase.itk_load_swig_module(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkBase.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkBase.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkBase.py", line 219, in itk_load_swig_module
    init_function()
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\itkVectorRescaleIntensityImageFilterPython.py", line 838, in unary_functor_image_filter_init_docstring
    if isinstance(itk.UnaryFunctorImageFilter, itkTemplate.itkTemplate):
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkLazy.py", line 78, in __getattribute__
    itkBase.itk_load_swig_module(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkBase.py", line 71, in itk_load_swig_module
    assert hasattr(this_module, "swig")
AssertionError
>>> itk.UnaryFunctorImageFilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkLazy.py", line 78, in __getattribute__
    itkBase.itk_load_swig_module(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkBase.py", line 71, in itk_load_swig_module
    assert hasattr(this_module, "swig")
AssertionError
```

**Comment by SimonRit** [comment]
Yes, I confirm what @MrTzschr said, nothing changed. The issue is still here with the latest release of ITKPythonPackage, see SimonRit/RTK#398. I have no idea where to look at to fix this, any suggestion?

**Comment by thewtex** [comment]
@MrTzschr thanks for the report -- @SimonRit thanks for the bisect. Putting the two together, this patch addresses the issue: https://github.com/InsightSoftwareConsortium/ITK/pull/2258
