### ISSUE TITLE
ITK Python Pool Threader deadlocks with multiprocess module

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#2069]
ITK Python is deadlocking when using with heavy weight process in the `multiprocess` python module.

The following is simplified from  SimpleITK/SimpleITK#1239.

The below code produces the deadlock for everything we have testing except MacOS with Python 3.8.

ITK Python version 5.1.post1 was used. 

```
#!/usr/bin/env python

import multiprocessing as mp
import numpy as np
import os
import threading
import itk

num_images = 2


def f( fname ):
    image = itk.imread(fname)


    print("Resampling {} pid: {} {}...".format(fname, os.getpid(), threading.get_ident(),fname))
    resampled = itk.resample_image_filter(image, reference_image=image, use_reference_image=True)

    return image # resampled


if __name__ == '__main__':

    paths = []
    for i in range(num_images):
        image = sitk.Image(10,11,12, sitk.sitkUInt8)
        path = f'/tmp/image_{i}.nii'
        sitk.WriteImage(image, path)
        paths.append(path)

    #print("GlobalDefaultThreader: {}".format(sitk.ProcessObject_GetGlobalDefaultThreader()))
    #print("GlobalNumberOfThreads: {}".format(sitk.ProcessObject_GetGlobalDefaultNumberOfThreads()))

    print("main pid: {} {}".format(os.getpid(), threading.get_ident()))


    f(paths[0])

    with mp.Pool(1) as p:
        p.map(f, paths)
```

Setting the global default threader to "platform" does not produce a deadlock.
Setting the resample to only use 1 work unit does not produce a deadlock.

It may be interesting to test ITK 4.x with the threader explicitly set to the pool.

**Comment by hjmjohnson** [comment]
I think this is related to #2003 .

I'm working through the python code now to get enough of an idea of how the magic works so that I can address this problem.  This might take a bit of time to complete as I have many other obligations right now.  Hopefully a solution can be implemented in the next few weeks.

Hans

**Comment by blowekamp** [comment]
@hjmjohnson The reading does not use ITK's multithreaded. This issue has been demonstrated to be dependent on using the Pool multithreaded, and setting the number of work units > 1. I think #2003 is not directly related to this issue.

**Comment by blowekamp** [comment]
I am not suspicion of what is occurring when forking a process which has thread, and the behavior of the *global* TheadPool being copied to the new process.

https://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by dzenanz** [comment]
Here is a pure ITK python version of that test case:
```py
#!/usr/bin/env python
import multiprocessing as mp
import numpy as np
import os
import threading
import itk

num_images = 2


def f(fname):
    image = itk.imread(fname)

    print("Resampling {} pid: {} {}...".format(fname, os.getpid(), threading.get_ident(),fname))
    resampled = itk.resample_image_filter(image, reference_image=image, use_reference_image=True)

    return image # resampled

if __name__ == '__main__':

    paths = []
    for i in range(num_images):
        image = itk.Image[itk.UC, 3].New()

        size = itk.Size[3]()
        size[0] = 10
        size[1] = 11
        size[2] = 12

        region = itk.ImageRegion[3]()
        region.SetSize(size)

        image.SetRegions(region)
        image.Allocate()
        path = f'image_{i}.nii'
        itk.imwrite(image, path)
        paths.append(path)

    print("main pid: {} {}".format(os.getpid(), threading.get_ident()))

    f(paths[0])

    with mp.Pool(1) as p:
        p.map(f, paths)
```
This is still failing.

**Comment by wyli** [comment]
this is still an issue in v5.2.0.post2 when used with pytorch's default multiprocessing loader:
```py
from torch import multiprocessing

try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass

import itk
import torch

if __name__ == "__main__":
    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass
```

output:
```
/usr/local/anaconda3/envs/py37/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/anaconda3/envs/py37/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/anaconda3/envs/py37/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/anaconda3/envs/py37/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

see also https://github.com/Project-MONAI/MONAI/issues/1629

**Comment by thewtex** [comment]
https://github.com/InsightSoftwareConsortium/ITK/pull/2552 addresses the issue reported by @wyli ,

but this test still hangs.

It will pass, though, by adding

```
import multiprocessing
try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass
```

changing the start method from *fork* to *spawn*.

**Comment by blowekamp** [comment]
Here is some additional information about the difference and the implications:
 - https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
 - https://britishgeologicalsurvey.github.io/science/python-forking-vs-spawn/

**Comment by dzenanz** [comment]
`spawn` doesn't do it for me. Below test program still crashes, both before and after #2552:
```py
#!/usr/bin/env python

import multiprocessing
try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass
    
import numpy as np
import os
import threading
import itk

num_images = 2


def f(fname):
    image = itk.imread(fname)

    print("Resampling {} pid: {} {}...".format(fname, os.getpid(), threading.get_ident(),fname))
    resampled = itk.resample_image_filter(image, reference_image=image, use_reference_image=True)

    return image # resampled

if __name__ == '__main__':

    paths = []
    for i in range(num_images):
        image = itk.Image[itk.UC, 3].New()

        size = itk.Size[3]()
        size[0] = 10
        size[1] = 11
        size[2] = 12

        region = itk.ImageRegion[3]()
        region.SetSize(size)

        image.SetRegions(region)
        image.Allocate()
        path = f'image_{i}.nii'
        itk.imwrite(image, path)
        paths.append(path)

    print("main pid: {} {}".format(os.getpid(), threading.get_ident()))

    f(paths[0])

    with multiprocessing.Pool(1) as p:
        p.map(f, paths)
```
Error message:
```text
(pyEnv) M:\a>python M:\a\itkPythonMultiProcessingTest.py
main pid: 17716 21460
Resampling image_0.nii pid: 17716 21460...
Resampling image_0.nii pid: 22024 11464...
Resampling image_1.nii pid: 22024 11464...
Traceback (most recent call last):
  File "M:\a\itkPythonMultiProcessingTest.py", line 50, in <module>
    p.map(f, paths)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<itk.itkImagePython.itkImageUC3; proxy of <Swig Object of type 'itkImageUC3 *' at 0x000001A446610570> >]'. Reason: 'TypeError("can't pickle SwigPyObject objects")'

(pyEnv) M:\a>
```

**Comment by blowekamp** [comment]
@dzenanz The error message it about the `itk.itkImage` not being able to be pickled. I don't believe it is related to threading. My example code was originally written in SimpleITK and I ported most of it to ITK Python. Matt's proposal does a appear to work around the PoolMultiThreader limitations with fork.

**Comment by dzenanz** [comment]
But why is pickling even attempted? It happens on `p.map(f, paths)`. With the following change the program finishes without crashing:
```py
    #with multiprocessing.Pool(1) as p:
    #    p.map(f, paths)
    for p in paths:
        f(p)
```

**Comment by blowekamp** [comment]
For interprocess communication Python `multiprocessing` pickles objects. Here I mean heavy weight processes, not threads. 

I did a quick google search for a quick explanatory docs/blog and the first two mixed up the Python GIL and multiprocessing.
