### ISSUE TITLE
PythonMedianImageFilterTest fails with numpy 1.21.0

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2613]
### Description

`PythonMedianImageFilterTest` fails after numpy is upgraded from 1.20.3 to the recently released 1.21.0.

### Steps to Reproduce

Enable `ITK_WRAP_PYTHON` and install `numpy==1.21.0`.

### Expected behavior

This test should not fail.

### Actual behavior

Fails with:

```none
2916: Traceback (most recent call last):
2916:   File "/home/matt/src/ITK/Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py", line 56, in <module>
2916:     type_hints = get_type_hints(itk.median_image_filter, globalns= { 'itk': itk })
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 1266, in get_type_hints
2916:     value = _eval_type(value, globalns, localns)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in _eval_type
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in <genexpr>
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in _eval_type
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in <genexpr>
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 270, in _eval_type
2916:     return t._evaluate(globalns, localns)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 520, in _evaluate
2916:     eval(self.__forward_code__, globalns, localns),
2916:   File "<string>", line 1, in <module>
2916: NameError: name 'dtype' is not defined
2916: itkTestDriver: Process exited with return value: 1```

### Reproducibility

Always.

### Versions

Current `master` or `release`, 5.2.0.

### Environment

Locally using Python 3.8.

### Additional Information

This seems to be related to the use of `numpy.typing.ArrayLike`.

**Comment by thewtex** [comment]
numpy issue: https://github.com/numpy/numpy/issues/19327

**Comment by thewtex** [comment]
Following `numpy` updates, we will be able to remove the constraint after 1.21.1 is released.
