### ISSUE TITLE
RawImageIO integers

### ISSUE THREAD

**Issue by ferdymercury** [InsightSoftwareConsortium/ITK#3184]
### Description

Hello,
I have a binary 2D image that I would like to read using `itk.RawImageIO`. 

However, I am unable to use it, because my format is integer instead of float.

Right now, it looks as if only floats are supported:

```
itk.RawImageIO.GetTypes()
<itkTemplate itk::RawImageIO>
Options:
  [<itkCType float>, 2]
  [<itkCType float>, 3]
```

### Impact analysis

Supporting shorts and ints should not affect much the size of the program, I believe.

### Expected behavior

Reading Integers from binary file is supported.

### Actual behavior

```
ImageIOType = itk.RawImageIO[itk.SS, 2]
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/itkTemplate.py", line 336, in __getitem__
    return(self.__template__[tuple(cleanParameters)])

KeyError: (<itkCType signed short>, 2)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/itkTemplate.py", line 340, in __getitem__
    return(self.__template__[tuple(cleanParameters)])

KeyError: (<itkCType signed short>, 2)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-52-cd00f1b021af>", line 1, in <module>
    ImageIOType = itk.RawImageIO[itk.SS, 2]

  File "/usr/local/lib/python3.6/dist-packages/itkTemplate.py", line 342, in __getitem__
    raise TemplateTypeError(self, tuple(cleanParameters))

TemplateTypeError: itk.RawImageIO is not wrapped for input type `itk.SS, int`.

To limit the size of the package, only a limited number of
types are available in ITK Python. To print the supported
types, run the following command in your python environment:

    itk.RawImageIO.GetTypes()

Possible solutions:
* If you are an application user:
** Convert your input image into a supported format (see below).
** Contact developer to report the issue.
* If you are an application developer, force input images to be
loaded in a supported pixel type.

    e.g.: instance = itk.RawImageIO[itk.F, int].New(my_input)

* (Advanced) If you are an application developer, build ITK Python yourself and
turned to `ON` the corresponding CMake option to wrap the pixel type or image
dimension you need. When configuring ITK with CMake, you can set
`ITK_WRAP_${type}` (replace ${type} with appropriate pixel type such as
`double`). If you need to support images with 4 or 5 dimensions, you can add
these dimensions to the list of dimensions in the CMake variable
`ITK_WRAP_IMAGE_DIMS`.

Supported input types:

itk.F
itk.F
```

### Versions

itk 5.1.2 installed via pip3 on Ubuntu 18

**Comment by dzenanz** [comment]
PRs are always welcome. Take inspiration from https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageGrid/wrapping/itkFlipImageFilter.wrap or https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageGrid/wrapping/itkConstantPadImageFilter.wrap.
