### ISSUE TITLE
Get error when importing `itk.itkGDCMImageIOPython`

### ISSUE THREAD

**Issue by lyhyl** [InsightSoftwareConsortium/ITK#3246]
### Description

Get ImportError when importing itk.itkGDCMImageIOPython in conda env (python 3.7).

### Steps to Reproduce

1. conda create -n itktest python=3.7
2. conda activate itktest
3. conda install -c conda-forge itk
4. python
5. import itk.itkGDCMImageIOPython as gdcm

### Expected behavior

import the package without any error.

### Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\anaconda3\envs\itktest\lib\site-packages\itk\itkGDCMImageIOPython.py", line 15, in <module>
    from . import _ITKIOGDCMPython
ImportError: PyCapsule_Import could not import module "_ITKCommonPython"
```

### Reproducibility

100%

### Versions

```
conda list | findstr itk
# packages in environment at C:\Users\user\anaconda3\envs\itktest:
itk                       5.2.0            py37h4038f58_0    conda-forge
itk-core                  5.2.0                    pypi_0    pypi
itk-filtering             5.2.0                    pypi_0    pypi
itk-numerics              5.2.0                    pypi_0    pypi
itk-registration          5.2.0                    pypi_0    pypi
```

### Environment

Windows 11
Python 3.7.11

### Additional Information

I also tested it in python 3.8, the same error presented.

**Comment by thewtex** [comment]
One 5.3rc4 is available on PyPI, it will be interesting to see if this persists per a recent patch from @tbirdso .

**Comment by dzenanz** [comment]
> One 5.3rc4 is available on PyPI

This is a misspelling. It should have read "Once 5.3rc4 is available on PyPI". 5.3rc4 is not tagged yet, and therefore not available on PyPI.

**Comment by dzenanz** [comment]
If Tom's suggestion works for you @lyhyl, please close the issue.

**Comment by lyhyl** [comment]
Yes, I can access it via lazy-loaded module.

The reason why I used to import it directly is that it makes intelligent code completion work. It is really painful to code without intelligent completion ☹️. From a perspective of users with C++ experience, importing what I need is reasonable.

If your team decides to keep this change, perhaps it should be documented because the behavior changed since 5.2.0.

**Comment by dzenanz** [comment]
Changes in undocumented behavior don't need to be documented 😄

Thanks for sharing your workaround. #3200 is tackling autosuggest improvements. Perhaps you could contribute with your review?

**Comment by thewtex** [comment]
> @dzenanz @thewtex do you have thoughts on what lies in/out of spec here?

@tbirdso yes, you are correct -- usually `itk.GDCMImageIO` is what is accessed in client code. `itk.itkGDCMImageIOPython` is an implementation detail.

@kian-weimer @hjmjohnson are working hard on the intelligent code completion support so no workarounds are necessary.
