### ISSUE TITLE
Building ITK on Mac M1 fails

### ISSUE THREAD

**Issue by MrMonk3y** [InsightSoftwareConsortium/ITK#3318]
### Description

I tried installing SimpleITK with pip. Which crasehd (first log bellow). I then proceeded to install ITK with pip which also failed (second log). Finally I decided to build ITK myself which wokred but somehow did not connect to python. Since there is no make uninstall I would actually prefer to install ITK with pip or homebrew. Tried latter as well but I did not build with python support. 

### Steps to Reproduce

```
pip install SimpleITK
pip install ITK
```

### Expected behavior

Should install the python package for python 3.10.
### pip SimpleITK Log:
```
      [ 63%] Creating directories for 'ITK'
      [ 65%] Performing download step (git clone) for 'ITK'
      Cloning into 'ITK'...
      fatal: remote error:
        The unauthenticated git protocol on port 9418 is no longer supported.
      Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
      Cloning into 'ITK'...
      fatal: remote error:
        The unauthenticated git protocol on port 9418 is no longer supported.
      Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
      Cloning into 'ITK'...
      fatal: remote error:
        The unauthenticated git protocol on port 9418 is no longer supported.
      Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
      -- Had to git clone more than once:
                3 times.
      CMake Error at ITK-prefix/tmp/ITK-gitclone.cmake:31 (message):
        Failed to clone repository:
        'git://github.com/InsightSoftwareConsortium/ITK.git'


      make[5]: *** [ITK-prefix/src/ITK-stamp/ITK-download] Error 1
      make[4]: *** [CMakeFiles/ITK.dir/all] Error 2
      make[3]: *** [all] Error 2
      make[2]: *** [SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build] Error 2
      make[1]: *** [CMakeFiles/SimpleITK-superbuild.dir/all] Error 2
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "/Users/me/Desktop/X23D/env/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 595, in setup
          cmkr.make(make_args, env=env)
        File "/Users/me/Desktop/X23D/env/lib/python3.10/site-packages/skbuild/cmaker.py", line 609, in make
          raise SKBuildError(

      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Source directory:
          /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-3et7dem2/simpleitk_3e3cd3b034754c2bb453b3160dbd8070
        Working directory:
          /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-3et7dem2/simpleitk_3e3cd3b034754c2bb453b3160dbd8070/_skbuild/macosx-12.0-arm64-3.10/cmake-build
      Please see CMake's output for more information.
      [end of output]
```

### pip ITK log:
```
 [  9%] Building CXX object Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/itkFloatingPointExceptions.cxx.o
      In file included from /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build/ITKs/Modules/Core/Common/src/itkFloatingPointExceptions.cxx:114:
      /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build/ITKs/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:140:3: error: use of undeclared identifier 'itk_feenableexcept'
        itk_feenableexcept (FE_DIVBYZERO);
        ^
      /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build/ITKs/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:141:3: error: use of undeclared identifier 'itk_feenableexcept'
        itk_feenableexcept (FE_INVALID);
        ^
      /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build/ITKs/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:163:3: error: use of undeclared identifier 'itk_fedisableexcept'
        itk_fedisableexcept (FE_DIVBYZERO);
        ^
      /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build/ITKs/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:164:3: error: use of undeclared identifier 'itk_fedisableexcept'
        itk_fedisableexcept (FE_INVALID);
        ^
      4 errors generated.
      make[5]: *** [Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/itkFloatingPointExceptions.cxx.o] Error 1
      make[4]: *** [Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/all] Error 2
      make[3]: *** [all] Error 2
      make[2]: *** [ITKp/src/ITK-stamp/ITK-build] Error 2
      make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 595, in setup
          cmkr.make(make_args, env=env)
        File "/opt/homebrew/lib/python3.10/site-packages/skbuild/cmaker.py", line 609, in make
          raise SKBuildError(

      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Source directory:
          /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859
        Working directory:
          /private/var/folders/yy/79cv2lvs6_qdl8_cjsz20c2c0000gn/T/pip-install-_vcq8xqw/itk_75e293e61a93459a8818550dc24cb859/_skbuild/macosx-12.0-arm64-3.10/cmake-build
      Please see CMake's output for more information.
      [end of output]
```

### Reproducibility
Always

### Versions

Python 3.10
clang-1300.0.29.3
cmake version 3.22.3

### Environment

None

### Additional Information
I using MacOS 12.1 on a Macbook Pro with M1 Max. No environment is active during the install. Python 3.10 is installed with Homebrew.

**Comment by MrMonk3y** [comment]
Yeah... Python 3.10 doens't work. Silly me. Downgraded to 3.8 and it seems to work now.

**Comment by e-simpson** [comment]
I'm getting this same issue on `Python 3.8.18` on an `M1 Pro` running `Sonoma 14.2.1`. 

@MrMonk3y did you do anything else to fix this?

**Comment by MrMonk3y** [comment]
@e-simpson  no only that.
