### ISSUE TITLE
Windows Python Module Import Failure

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITK#3425]
### Description

Windows Python CI fails due to failure to import `ITKImageIntensity` module in several Python CTests.

[CDash results](https://open.cdash.org/build/7906738)

### Expected behavior

Modules load successfully and CI passes

### Actual behavior

```py
Traceback (most recent call last):
  File "D:/a/1/s/Modules/Core/Mesh/wrapping/test/itkConnectedRegionsMeshFilterTest.py", line 28, in <module>
    threshold_filter = itk.BinaryThresholdImageFilter.IUC3IUC3.New()
  File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\lazy.py", line 138, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\base.py", line 96, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\base.py", line 132, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\base.py", line 291, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\..\ITKImageIntensityPython.py", line 13, in <module>
    from . import _ITKImageIntensityPython
ImportError: cannot import name '_ITKImageIntensityPython' from 'itk' (D:\a\1\s-build\Wrapping\Generators\Python\itk\__init__.py)
itkTestDriver: Process exited with return value: 1
```

### Versions

`master`

### Environment

Windows

**Comment by thewtex** [comment]
> It looks like we are not typically running Windows CI in PRs

Due to timeout's.

**Comment by tbirdso** [comment]
@thewtex Is it possible to increase the duration of the Azure Windows runners? I'm not sure what level of control we have.

**Comment by thewtex** [comment]
@tbirdso no, it is not.

**Comment by thewtex** [comment]
Note that work on C++20 modules aims to improve the build time to get us under the CI limit.

**Comment by tbirdso** [comment]
Having trouble recreating on my local Windows installation, tests are passing with a clean ITK Python build.

**Comment by tbirdso** [comment]
I am seeing the following warning when building ITK Python wrappings on Windows 2019 with Visual Studio 2022, perhaps related?

```none
2>------ Build started: Project: itk-stub-files, Configuration: RelWithDebInfo x64 ------
2>Generating .pyi files for Python wrapper interface
2>The system cannot execute the specified program.
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: Custom build for 'C:\repos\ITK-build-unstable\CMakeFiles\fa6a9a494588bf070abede55fcfc46ce\itk-stub-files.rule' exited with code 9020.
2>Done building project "itk-stub-files.vcxproj" -- FAILED.
```

**Comment by thewtex** [comment]
```
2>Generating .pyi files for Python wrapper interface
2>The system cannot execute the specified program.
```

I get the same error.

**Comment by dzenanz** [comment]
> why not reported in dashboard

There is no Windows Python build.

**Comment by tbirdso** [comment]
> There is no Windows Python build.

Not for PRs, but we do have a Windows Python CI pipeline for the `master` branch that is currently failing, hence this issue.

Continuous Windows Python dashboard result: [Windows_NT-Build3048-master-Python](https://open.cdash.org/build/7920550)

**Comment by tbirdso** [comment]
After more testing with the `itk-stub-files` target it looks like we may be running into issues with Windows clipping long arguments to 8192 characters.

At [https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/CMakeLists.txt#L170](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/CMakeLists.txt#L170) we define the `itk-stub-files` custom target which runs a Python script with several arguments. By adding a separate debugging target for debug printout and gradually removing arguments we find that the command fails only when the `GLOBAL_IdxFilesList` CMake variable is included as an argument.

We can define a custom debug target in the same file to interrogate how Windows receives this command argument:
```none
  add_custom_target(itk-stub-files-debug ALL
          COMMAND echo ${GLOBAL_IdxFilesList}
          COMMENT "Printing out GLOBAL_IdxFilesList argument"
          DEPENDS ${GLOBAL_IdxFilesList}
          VERBATIM
          )
```

The following is printed out when this target is built:
```
C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkFixedArray.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkCovariantVector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkPoint.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkTriangleHelper.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVariableSizeMatrix.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVersor.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_c_vector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_cost_function.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_diag_matrix.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_file_matrix.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_file_vector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_fortran_copy.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_least_squares_function.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_matrix_fixed.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_matrix_fixed_ref.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_matrix_ref.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_vector_ref.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_matrix.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_vector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/vnl_unary_function.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/ITKCommonBase.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkSize.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkOffset.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkArray.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkIndex.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkContinuousIndex.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkMatrix.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVectorContainer.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkMapContainer.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkBoundingBox.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkRGBPixel.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkRGBAPixel.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVariableLengthVector.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageRegion.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkSymmetricSecondRankTensor.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImage.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkVectorImage.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkNeighborhood.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageSourceCommon.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageSource.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageToImageFilterCommon.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageToImageFilterA.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageToImageFilterB.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkInPlaceImageFilterA.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkInPlaceImageFilterB.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkDefaultDynamicMeshTraits.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkDefaultStaticMeshTraits.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkFunctionBase.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkAnnulusOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkArray2D.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkBSplineInterpolationWeightFunction.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkBackwardDifferenceOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkDerivativeOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkDiffusionTensor3D.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkExtractImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkFloatingPointExceptions.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkForwardDifferenceOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkGaussianDerivativeOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkGaussianOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageBoundaryCondition.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageDuplicator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageKernelOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImageSink.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkImportImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkKernelFunctionBase.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkLaplacianOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkMetaDataObject.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkMinimumMaximumImageCalculator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkNeighborhoodOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkNumericTraits.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkOptimizerParameters.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkPointSet.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkPointSetToImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkSimpleDataObjectDecorator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkSobelOperator.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkSpatialFunction.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkStreamingImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkDenseFiniteDifferenceImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkFiniteDifferenceFunction.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkFiniteDifferenceImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkBinaryGeneratorImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkBoxImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkCastImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkNeighborhoodOperatorImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkNoiseImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkRecursiveSeparableImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkTernaryGeneratorImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkUnaryGeneratorImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkCurvatureFlowImageFilter.index.txt C:/repos/ITK-build-debug/Wrapping/Generators/Python/itk-pkl/itkMinMaxCurvatBuilding Custom Rule C:/repos/ITK/Wrapping/CMakeLists.txt
```

Scrolling to the end, it is clear that the list of index files is clipped in the middle of "itkMinMaxCurvature". Copying and pasting into a text editor, we see that this clip happens at column 8192, which coincides with Windows's command character limit. The same can be recreated by copying and pasting into a Command Prompt terminal on Windows.

By contract, the full value of `GLOBAL_IdxFilesList` can be obtained by printing the CMake list variable contents with `message` at configure time, which shows that the full string of index.txt files has 159,771 characters.

A few thoughts:
1. The list of `.index.txt` files appears to address every wrapped object in ITK. Perhaps this could be reduced to manageable chunks by refactoring into modules?
2. I am not a CMake expert, perhaps there is a way to overcome the Windows command length issue? However a 20x length increase seems significantly large.

cc @thewtex @kian-weimer @hjmjohnson

**Comment by tbirdso** [comment]
Assuming we do not want to bump straight to CMake to 3.21, I am taking a stab at refactoring into modules. As mentioned above, I certainly understand that this is a difficult change and will take time.

@kian-weimer @hjmjohnson Any discussion that you can contribute on particular pain points from your development iterations is welcomed. I will open a draft PR to track progress. I would also appreciate any tips you have on how to test that stub files are in fact working. It sounds like these changes are motivated by improving an IDE experience, do you have tips on what IDE you used and how you checked that stub file type hints worked on Linux/macOS?

@thewtex If it is critical that Windows Python builds in the next couple of days it may be necessary to consider reverting stub changes until resolved.

**Comment by thewtex** [comment]
We build the official macOS, Windows and Linux wheels with the Ninja generator. We generally limit the CMake version to the latest LTS version of Ubuntu -- Ubuntu 22.04 has cmake 3.22. So, we could update the CMake minimum version, but 5.4 is more appropriate for this, so folks will have time to upgrade. That said, #3444 is looking great!

**Comment by tbirdso** [comment]
Thanks @thewtex, good to hear there is another path. #3444 is looking promising, building locally on Windows now. I am hoping we will be able to proceed without changing build requirements.
