### ISSUE TITLE
Update data contribution process for new web3.storage

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#4340]
[web3.storage recently changed its interface](https://blog.web3.storage/posts/the-data-layer-is-here-with-the-new-web3-storage). Update our data upload process and docs accordingly.

**Comment by N-Dekker** [comment]
- Thanks for looking into this issue! Is there possibly any update? It's clearly a show-stopper for pull request #5836 (or any new test that required to have new data files, I guess).

**Comment by dzenanz** [comment]
The [instructions](https://github.com/InsightSoftwareConsortium/ITK/blob/main/Utilities/Maintenance/ExternalDataUpload/README.md#upload-a-single-file) don't work on Windows:
```log
C:\Dev\ITK-git>pixi run -e external-data-upload python Utilities/Maintenance/ExternalDataUpload/upload.py "C:/Dev/ITK-git/Testing/Data/Input/rf_voltage_15_freq_0005000000_2017-5-31_12-36-44_ReferenceSpectrum_side_lines_03_fft1d_size_128.mha" --testing-data-repo C:\Dev\ITKTestingData
==> Packing rf_voltage_15_freq_0005000000_2017-5-31_12-36-44_ReferenceSpectrum_side_lines_03_fft1d_size_128.mha into a CAR (unixfs-v1-2025 profile)...
==> Uploading to Filebase bucket 'itk-test-data'...
Traceback (most recent call last):
  File "C:\Dev\ITK-git\Utilities\Maintenance\ExternalDataUpload\upload.py", line 386, in <module>
    raise SystemExit(main())
                     ~~~~^^
  File "C:\Dev\ITK-git\Utilities\Maintenance\ExternalDataUpload\upload.py", line 351, in main
    cid = upload_file_to_filebase(abs_path, bucket, access_key, secret_key)
  File "C:\Dev\ITK-git\Utilities\Maintenance\ExternalDataUpload\upload.py", line 155, in upload_file_to_filebase
    local_cid = build_car(input_path, car_path)
  File "C:\Dev\ITK-git\Utilities\Maintenance\ExternalDataUpload\upload.py", line 45, in build_car
    result = subprocess.run(
        [
    ...<11 lines>...
        check=True,
    )
  File "C:\Dev\ITK-git\.pixi\envs\external-data-upload\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ITK-git\.pixi\envs\external-data-upload\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ITK-git\.pixi\envs\external-data-upload\Lib\subprocess.py", line 1554, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I was able to follow them on Ubuntu.
