### ISSUE TITLE
libtbb missing from some ITK 5.4.0 wheels

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#4713]
On my old linux box, pip install itk does not work anymore because libtbb is missing. Here is the list of commands I execute and the relevant output:
```
srit@russula:~> conda env create -y --name py39 python=3.9
srit@russula:~> conda activate py39
(py39) srit@russula:~> pip install itk
Collecting itk
  Using cached itk-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-core==5.4.0 (from itk)
  Using cached itk_core-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-numerics==5.4.0 (from itk)
  Using cached itk_numerics-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-io==5.4.0 (from itk)
  Using cached itk_io-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-filtering==5.4.0 (from itk)
  Using cached itk_filtering-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-registration==5.4.0 (from itk)
  Using cached itk_registration-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting itk-segmentation==5.4.0 (from itk)
  Using cached itk_segmentation-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl.metadata (22 kB)
Collecting numpy (from itk)
  Using cached numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached itk-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (17 kB)
Using cached itk_core-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (80.5 MB)
Using cached itk_filtering-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (67.5 MB)
Using cached itk_io-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (26.1 MB)
Using cached itk_numerics-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (56.2 MB)
Using cached itk_registration-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (27.2 MB)
Using cached itk_segmentation-5.4.0-cp39-cp39-manylinux_2_17_x86_64.whl (14.7 MB)
Using cached numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Installing collected packages: numpy, itk-core, itk-numerics, itk-io, itk-filtering, itk-segmentation, itk-registration, itk
Successfully installed itk-5.4.0 itk-core-5.4.0 itk-filtering-5.4.0 itk-io-5.4.0 itk-numerics-5.4.0 itk-registration-5.4.0 itk-segmentation-5.4.0 numpy-1.26.4
(py39) srit@russula:~> python
Python 3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import itk
i>>> itk.Image[itk.F, 3].New()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/support/lazy.py", line 138, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/support/base.py", line 94, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/support/base.py", line 130, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/support/base.py", line 289, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/support/../ITKPyBasePython.py", line 63, in <module>
    from itk.pyBasePython import *
  File "/home/srit/miniconda3/envs/py39/lib/python3.9/site-packages/itk/pyBasePython.py", line 15, in <module>
    from . import _ITKCommonPython
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
>>> 
(py39) srit@russula:~> find miniconda3/envs/py39 -name libtbb*
(py39) srit@russula:~> 
```

**Comment by SimonRit** [comment]
I had a similar problem when building RTK wheels. The problem seems to be caused by the recent upgrade of scikit-build-core from 0.8.2 to 0.9.5. [Downgrading](https://github.com/SimonRit/ITKPythonPackage/commit/766eaae6ba783d92ded30e8379de8bef981bd041) it produces a wheel with libtbb. The main difference I observe is that 0.9.5 does not move a linux wheel at the end (see [here](https://github.com/RTKConsortium/RTK/actions/runs/9542327695/job/26306897724#step:4:2476)) whereas 0.8.2 replaces the manylinux file with linux file (see [here](https://github.com/RTKConsortium/RTK/actions/runs/9562250904/job/26358236471#step:4:2850)). I don't know what's the solution but that might help...

**Comment by thewtex** [comment]
CC @henryiii @jcfr

**Comment by SimonRit** [comment]
Any update on this issue?

**Comment by thewtex** [comment]
We will address this in 5.4.1.

**Comment by thewtex** [comment]
In the 5.4.2 `itk-core` wheels libtbb is present at `itk_core.libs/libtbb-f489fd38.so.12.9`.

**Comment by dzenanz** [comment]
I assume you will upload the 5.4.2 wheels to [PyPI](https://pypi.org/project/itk/#files) soon?

**Comment by SimonRit** [comment]
That's great, thank you! Do you know why it works now?
Just to be sure, if I remember correctly, only some of the wheels had this issue, those compiles with manylinux_2_17.

**Comment by dzenanz** [comment]
5.4.2 wheels are up! 🥳 

Linux wheels seem to be missing?

**Comment by thewtex** [comment]
`itk-5.4.2` had to be yanked due to auditwheel issues. We will have to create an `itk-5.4.2.post1`.

In the meantime, this issue can be tested with `itk-core-5.4.2`, which is still available.

**Comment by SimonRit** [comment]
The problem is still present in the remote modules unfortunately:
LinuxWheel310_2_28-x64.zip @ https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/13337180490
LinuxWheel311_2_28-x64-cuda116.zip @ https://github.com/RTKConsortium/ITKCudaCommon/actions/runs/13408785111

**Comment by thewtex** [comment]
@SimonRit 

libtbb is present in the `itk-core` wheels, as expected. Download, e.g.

https://files.pythonhosted.org/packages/48/f1/50b3441d5c5ca77470e608e32322a35f0f242d27e7ace21c1ba1276f8818/itk_core-5.4.2.post1-cp311-abi3-manylinux_2_28_x86_64.whl

unpack it (it is a ZIP file). The wheel is `itk_core.libs/libtbb-3c88584c.so.12.9`.

This is the only wheel that should be shipping libtbb. All the other packages, itk and itk remote module packages, depend on this package and they load the shared library at import time. This ensure threads are used across modules, etc.

Something else is going on. I tried the `itk-splitcomponents` wheels locally, and they worked fine for me.

Are you able to reproduce the issue locally?

**Comment by SimonRit** [comment]
Thanks @thewtex for quickly getting back to me. Yes I can reproduce the issue. I did
```bash
$ unzip LinuxWheel311_2_28-x64.zip
$ conda create -y --name testsplit python=3.11
$ conda activate testsplit
$ pip install itk_splitcomponents-2.2.1-cp311-abi3-manylinux_2_28_x86_64.whl
$ echo -e "from itk import SplitComponents\nhelp(SplitComponents)" | python
libtbb.so.12: cannot open shared object file: No such file or directory
```
I'm surprised you can use the wheels locally. And I also observed that I get multiple libtbb
```bash
$ find -name *libtbb*
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_filtering.libs/libtbb-3c88584c.so.12.9
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_io.libs/libtbb-3c88584c.so.12.9
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_numerics.libs/libtbb-3c88584c.so.12.9
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_registration.libs/libtbb-3c88584c.so.12.9
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_segmentation.libs/libtbb-3c88584c.so.12.9
/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_core.libs/libtbb-3c88584c.so.12.9
```
but not in splitcomponents
```bash
$ ls /home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_splitcomponents-2.2.1.dist-info/itk_splitcomponents.libs
ls: cannot access '/home/srit/miniconda3/envs/testsplit/lib/python3.11/site-packages/itk_splitcomponents-2.2.1.dist-info/itk_splitcomponents.libs': No such file or directory
```
