### ISSUE TITLE
ITKrc02 python regressions

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#842]
### Steps to Reproduce

```bash
pip install itk --pre
python -c 'import itk; itk.force_load()'
```
```none
Traceback (most recent call last):
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkBase.py", line 85, in LoadModule
    module_data[name]
KeyError: 'ITKQuadEdgeMesh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkExtras.py", line 115, in force_load
    getattr(itk, k)
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkLazy.py", line 44, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkBase.py", line 118, in LoadModule
    LoadModule(dep, namespace)
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkBase.py", line 118, in LoadModule
    LoadModule(dep, namespace)
  File "/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itkBase.py", line 87, in LoadModule
    file = inspect.getfile(this_module)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 647, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'ITKQuadEdgeMesh'> is a built-in module
```

### Actual behavior

```none
```

### Reproducibility

100%

### Versions
```
pip install itk==5.0rc2
```
### Environment

Mac

python3.7

**Comment by maekclena** [comment]
My guess would be a corrupted installation. @hjmjohnson can you check that the file `/Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshConfig.py` exists?

**Comment by hjmjohnson** [comment]
@maekclena . 
```bash

# ITKQuadEdgeMeshFilteringConfig.py  exists
# ITKQuadEdgeMeshConfig.py .             does not exist

ls -alrth /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshConfig.py
ls: /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshConfig.py: No such file or directory

ls -alrth /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshFilteringConfig.py 
-rw-rw-r--  1 johnsonhj  IOWA\Engineering-Electrical-Computer-Engineering-D2800   6.4K May  7 15:45 /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshFilteringConfig.py

ls -al  /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/*Quad*
-rw-rw-r--  1 johnsonhj  IOWA\Engineering-Electrical-Computer-Engineering-D2800  6569 May  7 15:45 /Users/johnsonhj/.venv/miatt/lib/python3.7/site-packages/itk/Configuration/ITKQuadEdgeMeshFilteringConfig.py
```

Is there anything else I should checkout

**Comment by fbudin69500** [comment]
@hjmjohnson Would it be possible for you to try again to install the package in a clean environment?
I ran `find` in the python package directory and I got:
```
find . -iname \*Quad\*
./numpy/.dylibs/libquadmath.0.dylib
./itk/_ITKQuadEdgeMeshPython.so
./itk/ITKQuadEdgeMeshPython.py
./itk/Configuration/ITKQuadEdgeMeshFilteringConfig.py
./itk/Configuration/__pycache__/ITKQuadEdgeMeshFilteringConfig.cpython-37.pyc
./itk/Configuration/__pycache__/ITKQuadEdgeMeshConfig.cpython-37.pyc
./itk/Configuration/ITKQuadEdgeMeshConfig.py
./itk/itkQuadEdgeMeshLineCellPython.py
./itk/itkQuadEdgeMeshPointPython.py
./itk/itkQuadEdgeMeshTraitsPython.py
./itk/itkQuadEdgePython.py
./itk/itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterPython.py
./itk/itkDiscreteCurvatureTensorQuadEdgeMeshFilterPython.py
./itk/itkDiscreteCurvatureQuadEdgeMeshFilterPython.py
./itk/itkBorderQuadEdgeMeshFilterPython.py
./itk/__pycache__/itkBorderQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkDiscreteMinimumCurvatureQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeMeshLineCellPython.cpython-37.pyc
./itk/__pycache__/itkSmoothingQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/ITKQuadEdgeMeshPython.cpython-37.pyc
./itk/__pycache__/ITKQuadEdgeMeshFilteringPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgePython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeCellTraitsInfoPython.cpython-37.pyc
./itk/__pycache__/itkCleanQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkDiscreteMaximumCurvatureQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeMeshBasePython.cpython-37.pyc
./itk/__pycache__/itkGeometricalQuadEdgePython.cpython-37.pyc
./itk/__pycache__/itkDiscreteCurvatureQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkDelaunayConformingQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeMeshPointPython.cpython-37.pyc
./itk/__pycache__/itkDiscreteMeanCurvatureQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeMeshTraitsPython.cpython-37.pyc
./itk/__pycache__/itkDiscreteCurvatureTensorQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/__pycache__/itkQuadEdgeMeshToQuadEdgeMeshFilterPython.cpython-37.pyc
./itk/itkQuadEdgeMeshToQuadEdgeMeshFilterPython.py
./itk/itkQuadEdgeMeshBasePython.py
./itk/itkCleanQuadEdgeMeshFilterPython.py
./itk/itkSmoothingQuadEdgeMeshFilterPython.py
./itk/itkDiscreteMinimumCurvatureQuadEdgeMeshFilterPython.py
./itk/itkDiscreteMeanCurvatureQuadEdgeMeshFilterPython.py
./itk/_ITKQuadEdgeMeshFilteringPython.so
./itk/itkGeometricalQuadEdgePython.py
./itk/itkDiscreteMaximumCurvatureQuadEdgeMeshFilterPython.py
./itk/itkDelaunayConformingQuadEdgeMeshFilterPython.py
./itk/itkQuadEdgeCellTraitsInfoPython.py
./itk/ITKQuadEdgeMeshFilteringPython.py
./itk/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterPython.py
```

And the file `ITKQuadEdgeMeshConfig.py` was installed on the Mac on which I tested the package.

**Comment by thewtex** [comment]
The `KeyError: 'ITKQuadEdgeMesh'` error oddly comes up sometimes where there are unrelated packaging issues. We had an error in the `itk-5.0rc2` packages, which has now been resolved. I check the package from May 15th, and they did not have an issues with `itk.force_load()`, so closing this. @hjmjohnson thanks for the report :+1: .
